### ISSUE TITLE
Sync not matching some methods

### ISSUE THREAD

**Issue by gregoriohc** [themsaid/laravel-langman#52]
Sync is ignoring @lang and @choice if they are used just after an HTML tag.
For example: `<p>@lang('language.line')</p>`
The problem is that the regex is ignoring them because the first part: `[^\w|>]`
Is that the expected behavior?
I have been playing with the regex in https://regex101.com/r/jS5fX0/2 but I'm not sure how to solve this in the right way.

**Comment by joelcuevas** [comment]
I was wondering about this same thing today...

The regex is explicitly ignoring anything that starts with an `>` (because `->trans('lang.line')`), but this causes a lot of trouble with Blade one-liners as the one stated by @gregoriohc.

Maybe this could be fixed with a negative lookbehind on the `>` char to assert that it doesn't have a `-` before. Something like this: https://regex101.com/r/jS5fX0/3.

What dou you think @themsaid?

**Comment by themsaid** [comment]
That regex here would fix it (https://regex101.com/r/jS5fX0/3) I believe, are you willing to make a PR? :)

**Comment by joelcuevas** [comment]
Of course. Done!
